name: todo_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  webview_flutter: ^3.0.0
  intl: ^0.17.0
  date_picker_timeline: ^1.2.3
  get: ^4.6.5
  grouped_list: ^4.2.0
  url_launcher: ^6.0.12
  flutter_svg: ^0.19.1
  geolocator: ^8.2.0
  google_maps_flutter: ^2.1.2
  flutter_spinkit: ^5.1.0
  flutter_typeahead: ^3.2.4
  flutter_launcher_name: ^0.0.1
  card_swiper: ^2.0.3
  carousel_slider: ^4.1.1
  dots_indicator: ^2.1.0
  expansion_card: ^0.1.0
  auto_size_text: ^3.0.0
  flutter_rating_stars: ^1.0.3+4
  shared_preferences: ^2.0.15
  lottie: ^1.3.0
  introduction_screen: ^3.0.2
  fluttertoast: ^8.0.9
  flutter_slidable: ^1.3.0
  cached_network_image: ^3.2.0
  expansion_tile_card: ^2.0.0
  rflutter_alert: ^2.0.4
  flutter_html: ^0.8.2
  dart_date: ^1.1.1
  file_picker: ^4.6.1
  path_provider: ^2.0.11
  open_file: ^3.2.1
  dio:
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_name:
  name: "SmartCampus"
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/font/
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/font/Raleway-Regular.ttf
        - asset: assets/font/Raleway-Bold.ttf
          weight: 700
        - asset: assets/font/Raleway-SemiBold.ttf
        - asset: assets/font/Raleway-Medium.ttf
          weight: 300

    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-SemiBold.ttf
        - asset: assets/font/Poppins-Medium.ttf
          weight: 300

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
